<?php


namespace app\admin\controller;


use app\common\controller\AdminBase;
use app\common\model\Newscenic as NewscenicModel;
use app\common\model\Example; //地区
use think\Config;
use think\Db;
use think\Request;
class Newscenic extends AdminBase {
    private $newScenicModel;

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->newScenicModel =new NewscenicModel;
    }

    public function index($keyword='',$page=1)
    {
        $map = [];
        if ($keyword) {
            $map['s.name_cn'] = ['like', "%{$keyword}%"];
        }
        $field = [
            'c.name as cname',
            's.name_cn',
            's.name_kr ',
            's.id',
            's.img',
            's.city',
            's.content_cn',
            's.content_kr',
            's.Hits'
        ];
        $data = NewscenicModel::alias('s')
            ->join('_Example_ c', 's.classid=c.id')
            ->field($field)
            ->where($map)
            ->order('id', 'desc')
            ->paginate(15, false, ['query' => ['page'=>$page,'keyword'=>$keyword]]);
        $this->assign("keyword",$keyword);

        return $this->fetch('', ['data' => $data]);

    }
    public function add(){
        return $this->fetch();
    }


    /*
    *接受表单的数据
     */
    public function save()
    {
        $data = $this->request->post();

        if (empty($data['img'])){
            return  $this->error('添加失败,请上传图片');
        }
        $data['create_time'] = date('Y-m-d H:i:s');
        $data['update_time'] = date('Y-m-d H:i:s');
        $data['img'] = implode(",",$data['img']);
        $success = $this->newScenicModel->allowField(true)->save($data);
        if ($success) {
            return $this->success('添加成功');
        }else{
            return $this->error('添加失败,请重试');
        }
    }



    public function edit($id)
    {
        $scenic = $this->newScenicModel->find($id);
        $map = Example::select();
        $where['id'] = $scenic['classid'];
        $img = Example::field('img')->find();
        $scenic['img'] = explode(',',$scenic['img']);
        return $this->fetch('edit',['scenic'=>$scenic,'map'=>$map,'img'=>$img]);
    }

    public function update()
    {
        $data = $this->request->post();
        $data['update_time']=date('Y-m-d H:i:s');
        if (empty($data['img'])){
            return  $this->error('添加失败,请上传图片');
        }
        $data['img'] = implode(",",$data['img']);
        if ($data) {
            $success = NewscenicModel::where('id',$data['id'])->update($data);
            if ($success) {
                return $this->success('修改成功');
            }else{
                return $this->error('修改失败,请重试');
            }
        }
    }
    public function delete($id)
    {
        $success = NewscenicModel::where('id',$id)->delete();
        if ($success) {
            return $this->success('删除成功');
        }else{
            return $this->error('删除失败,请重试');
        }
    }


}